version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket pipeline-bucket1 --output-template-file outputsamtemplate.yml
artifacts:
  files:
    - template.yaml
    - outputsamtemplate.yml
